### ISSUE TITLE
Handle Non-Ascii unicode characters.

### ISSUE THREAD

**Issue by saurabhshri** [MatejMecka/captionsTranslator#1]
```
python captionsTranslator.py -i ../ST.srt -o lol.srt -lf EN -lt ES
1 <i>Antes de Star Trek: Descubrimiento... </i>Necesito un equipo que me ayude.
2 Y eso te incluye a ti.
3 Acepto.
4 Salir de aquí, siempre fue un trabajo de dos hombres.
Traceback (most recent call last):
  File "captionsTranslator.py", line 86, in <module>
    main()
  File "captionsTranslator.py", line 83, in main
    parsefiles(args.input_file, args.output_file, args.language_from, args.language_to)
  File "captionsTranslator.py", line 72, in parsefiles
    handleTranslations(tempFile.name, outputFile, languageFrom, languageTo)
  File "captionsTranslator.py", line 54, in handleTranslations
    translate(inp, out, laf, lat)
  File "captionsTranslator.py", line 24, in translate
    fileresp.write("{}\n{} --> {}\n{}\n\n".format(sub.index,str(sub.start)[:-3], str(sub.end)[:-3], translationSentence))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 12: ordinal not in range(128)
```

File : 
[ST.txt](https://github.com/MatejMecka/captionsTranslator/files/1585512/ST.txt)

**Comment by MatejMecka** [comment]
Use python3 python2 is going to be deprecated and python2 doesn't support utf8 as great as python3

**Comment by MatejMecka** [comment]
For me it works. All I did was use python3 so yeah 
[output.txt](https://github.com/MatejMecka/captionsTranslator/files/1585766/output.txt)

**Comment by saurabhshri** [comment]
Thanks!
